[project]
name = "Grading_Posting_Script"
authors = [{name = "TriHardStudios", email="gjbell@trihardstudios.com"}]
version = "1.1.0"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["Grade", "FileHelpers"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

