"""
This module contains functions used to manually edit students scores after they are generated by ``Grade.score``
This is useful for when a scoring error occurs. This should be the last step before posting.
"""

raise NotImplementedError("Manual Editing of student scores is not implemented")
